### PR TITLE
[Migrate CI] Added workflow for GitHub actions CI. Deleted travis.yml.

### LINKED ISSUE #1255: Move Multicloud  CI to Github Actions from Travis.
**Issue/Feature Description:**
Move Multicloud CI to Github Actions from Travis.

**Why this issue to fixed / feature is needed(give scenarios or use cases):**

**How to reproduce, in case of a bug:**

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

### PR DESCRIPTION
**Pull request by anvithks**
**What type of PR is this?**
 /kind enhancement

**What this PR does / why we need it**:
Addsed the GitHub Actions workflow file
**Which issue(s) this PR fixes**:

Fixes #1255 

**Test Report Added?**:
 /kind TESTED

**Test Report**:
The workflow run can be seen in the Actions tab.
The codecov report is added below.
**Special notes for your reviewer**:

### CODE REVIEW

**Comment by rajat-soda** [comment]
as discussed in standup .. this needs to be fixed before merge : Travis CI - Pull Request Expected — Waiting for status to be reported
Over all looks good.

**Review by rajat-soda — COMMENTED** [review]
This needs to be resolved before merge  : Travis CI - Pull Request Expected — Waiting for status to be reported

**Comment by anvithks** [comment]
> This needs to be resolved before merge : Travis CI - Pull Request Expected — Waiting for status to be reported

@rajat-soda We will be removing the Travis integration across the organization. Should be fixed then.

**Comment by rajat-soda** [comment]
LGTM

**Review by kumarashit — APPROVED** [review]
LGTM

**Review by rajat-soda — APPROVED** [review]
LGTM

**Review by skdwriting — APPROVED** [review]
LGTM

**Comment by skdwriting** [comment]
CI migration in progerss to github actions, local ci ok. hence merging.

**Pull request merged**
