### PR TITLE
Issuefix : Storage Class not displayed, mgo driver removal

### PR DESCRIPTION
**Pull request by josephjacobmorris**
**What type of PR is this?**
> /kind bug fix

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
- Storage Class not displayed
- Remove additional log line
Fixes #
#1389

**Test Report Added?**:
> /kind TESTED

**Test Report**:
- Storage Class is not displayed fix
image

- mgo driver removed from metadatamangement
image

**Special notes for your reviewer**:

### CODE REVIEW

**Review by josephjacobmorris — COMMENTED** [review]
Self-review done

**Comment by devanshjain7** [comment]
LGTM

**Review by devanshjain7 — APPROVED** [review]
LGTM

**Review by PravinRanjan10 — APPROVED** [review]
LGTM

**Pull request merged**
