### PR TITLE
Fix and enable CI for go formatting issues

### LINKED ISSUE #1244: Fix go formatting issues
**Issue/Feature Description:**
The issue is opened for correcting all formatting issues in multi-cloud project.

**Why this issue to fixed / feature is needed(give scenarios or use cases):**
- Golang standard formatting
- Formatted code all helps to generate nice doc with ```go doc ``` commands
 
**How to reproduce, in case of a bug:**
use ```go fmt``` to check all formatting issues 
**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**
Note:
It is good to use ```goimports``` as it is superset of 
- go formatting 
- imports are grouped into sections

### PR DESCRIPTION
**Pull request by AmitRoushan**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Fix go formatting issues
The PR also adds up go formatting issue handling in makefile.
- Install goimports 
  ```go get golang.org/x/tools/cmd/goimports```
- For formatting error check
  ``` make CHECK_ERROR=y goimports```
- For fommatting error fix
  ```make goimports```  

**Which issue(s) this PR fixes**:

Fixes #1244 

**Test Report Added?**:
/kind NOT-TESTED

**Test Report**:

NA
**Special notes for your reviewer**:
Note: 
It is good to use``` goimports``` as it is superset of

go formatting
imports are grouped into sections

### CODE REVIEW

**Comment by AmitRoushan** [comment]
@kumarashit @rajat-soda @PravinRanjan10 PTAL

**Comment by rajat-soda** [comment]
LGTM

**Comment by kumarashit** [comment]
@AmitRoushan Suggestion: can we split this into two commits 1) for .travis and Makefile changes and 2) all the formatted files. Mention this in the PR comment. This will help any member checking the PR and can understand the reason for so many file changes easily

**Comment by AmitRoushan** [comment]
@kumarashit Updated PR as per suggestion. PTAL

**Review by kumarashit — COMMENTED** [review]
Please resolve conflicts.
Changes looks fine

**Comment by AmitRoushan** [comment]
@kumarashit Conflicts are resolved and a new task added in CI for Golang Formatting. PTAL

**Review by kumarashit — APPROVED** [review]
LGTM

**Review by skdwriting — APPROVED** [review]
LGTM

**Pull request merged**
