### PR TITLE
adding code coverage default settings

### PR DESCRIPTION
**Pull request by kumarashit**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
/kind new feature
> /kind bug fix
> /kind cleanup
> /kind revert change
> /kind design
> /kind documentation
> /kind enhancement

**What this PR does / why we need it**:
Adds codecoverage default settings for code coverage

**Which issue(s) this PR fixes**:

Fixes #

**Test Report Added?**:
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
> /kind TESTED
> /kind NOT-TESTED

**Test Report**:

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by rajat-soda** [comment]
LGTM

**Review by rajat-soda — APPROVED** [review]
LGTM

**Review by skdwriting — APPROVED** [review]
LGTM

**Comment by kumarashit** [comment]
Closing this PR as these changes will be included by @rajat-soda in PR #1082

**Pull request closed without merging**
