### PR TITLE
multicloud Tets automation framework

### PR DESCRIPTION
**Pull request by kumarashit**
**What this PR does / why we need it**: This is the test automation framework for Multilcloud.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:
Authored by @rhsakarpos This is in its initial phase and the framework will be updated as per the need
Written in Java
**Release note**:

```release-note
```

### CODE REVIEW

**Comment by sfzeng** [comment]
Hi @kumarashit , is this the normal way to build automation test framework?

**Comment by kumarashit** [comment]
> Hi @kumarashit , is this the normal way to build automation test framework? Can we give any examples about it?

Hi @sfzeng , this is something which was presented in the community and few contributors have started working on it. So i assume it to be a good way to start. But still we can improve this framework as and when required. @rhsakarpos Please let us know your opinion

**Comment by wisererik** [comment]
I saw many jar package and .class files, are their licenses valid?

**Comment by himanshuvar** [comment]
Please do not include binaries in the PR.
Please consider to make the project build framework independent of binaries. We can use any of the available framework like Maven, Gradle etc.

**Comment by himanshuvar** [comment]
And Also, Please do not include .class file for PR

**Comment by rhsakarpos** [comment]
> Hi @kumarashit , is this the normal way to build automation test framework? Can we give any examples about it?

hi, this is normal, yes, is it usual ? well, there are standard frameworks i guess, but how to put them together is up to anyone ...so here, the need is

1. to have a way to give inputs in a file for various test cases
-- used json input format here
2. to be able to run the same test with these various inputs
- wrote some java code here, since in my case, i can work faster in java than in golang
3. to get the result and report it
-- used junit  here, known devil, YMMV

however, please suggest any alternatives, improvements, changes, will roll them in

**Comment by rhsakarpos** [comment]
> And Also, Please do not include .class file for PR

yes, @kumarashit can you please remove the class files. initially, i had committed them in error to my personal repo, will remove from there too

**Comment by rhsakarpos** [comment]
> Please do not include binaries in the PR.
> Please consider to make the project build framework independent of binaries. We can use any of the available framework like Maven, Gradle etc.

True, @Puja was working on a Maven build for this

**Comment by rhsakarpos** [comment]
> I saw many jar package and .class files, are their licenses valid?

yes @wisererik, however, since we are now adding it here, will double check

**Comment by kumarashit** [comment]
> > And Also, Please do not include .class file for PR
> 
> yes, @kumarashit can you please remove the class files. initially, i had committed them in error to my personal repo, will remove from there too

Yes, i have removed it now. Didn't notice the class files earlier.

**Comment by kumarashit** [comment]
> > Please do not include binaries in the PR.
> > Please consider to make the project build framework independent of binaries. We can use any of the available framework like Maven, Gradle etc.
> 
> True, @puja was working on a Maven build for this

Yes, Puja and Rahul from C2C are working on the gradle build. So IMO, we can merge this code and they can add the gridle fw over this part of the code. Thanks

**Comment by kumarashit** [comment]
> > And Also, Please do not include .class file for PR
> 
> yes, @kumarashit can you please remove the class files. initially, i had committed them in error to my personal repo, will remove from there too

Done

**Comment by kumarashit** [comment]
@all, this piece of code from @rhsakarpos is to provide a basic f/w. This is important to push this code.  People in community are ready to take this and add all the build f/w and enhancements.

**Comment by kumarashit** [comment]
Not required. Test framework is moved into new repo called 'qa'

**Pull request closed without merging**
