### PR TITLE
Update go micro dependency references and related code

### LINKED ISSUE #970: Update micro dependency and code changes.
**Issue/Feature Description:** old micro packages are used in the multi-cloud.

**Why this issue to fixed / feature is needed(give scenarios or use cases):** The issue is required to update the micro dependent code in multi-cloud

**How to reproduce, in case of a bug:**

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

### PR DESCRIPTION
**Pull request by himanshuvar**
**What type of PR is this?**
> /kind enhancement

**What this PR does / why we need it**:  This PR to update go micro dependency references updates which includes the following:

> 1. Update go micro v2 import paths.
> 2. Updated the micro file naming according to protoc-gen-micro for generating the concrete go implementation for proto definitions.
> 3. Update generated micro files w.r.t  go micro v2 changes.
> 4. Optimize/Sort Imports.
> 5. Update vendor packages for go micro

**Which issue(s) this PR fixes**:

Fixes #970 

**Test Report Added?**:
> /kind TESTED

**Test Report**:

Basic Multi-Cloud Feature Testing is done.

- [x] 1. Backend Creation
- [x] 2. Backend Listing
- [x] 3. Backend Get
- [x] 4. Backend Delete
- [x] 5. Bucket Creation
- [x] 6. Bucket Listing
- [x] 7. Bucket Get
- [x] 8. Bucket Delete
- [x] 9. Object Upload
- [x] 10. Object Download
- [x] 11. Object Delete
- [x] 12. Migration Plan Creation
- [x] 13. Migration Plan Listing
- [x] 14. Migration Plan Get
- [x] 15. Migration Plan Delete
- [x] 16. Migration Job Execution
- [x] 17. Migration Job Listing
- [x] 18. Migration Job Get
- [x] 19. Muliti-Part Upload
- [x] 20. Multi-Part Download from AWS console
- [x] 21. Multi-Cloud SSE

Migration Job is successful with the following known issues.
These issues are still there after elba. 
https://github.com/sodafoundation/multi-cloud/issues/952
https://github.com/sodafoundation/multi-cloud/issues/940

SSE is not working as per the Code available from multi-cloud. I have opened an issue.
https://github.com/sodafoundation/multi-cloud/issues/986

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by sfzeng** [comment]
Hi @himanshuvar Could you please also add test for SSE feature?

**Comment by himanshuvar** [comment]
> Hi @himanshuvar Could you please also add test for SSE feature?

@sfzeng I don't know much about mult-cloud SSE. Could you please guide me the steps or a Demo for testing SSE?

**Comment by sfzeng** [comment]
> > Hi @himanshuvar Could you please also add test for SSE feature?
> 
> @sfzeng I don't know much about mult-cloud SSE. Could you please guide me the steps or a Demo for testing SSE?

yes, please check api/pkg/s3/bucketsseput.go.

**Comment by himanshuvar** [comment]
> > > Hi @himanshuvar Could you please also add test for SSE feature?
> > 
> > 
> > @sfzeng I don't know much about mult-cloud SSE. Could you please guide me the steps or a Demo for testing SSE?
> 
> yes, please check api/pkg/s3/bucketsseput.go.

@sfzeng I am not able to figure the API call request/response. Please provide the API spec for SSE.

<Bucket>
            <Name>bucket1</Name>
            <CreationDate>2020-04-10T20:20:08.000Z</CreationDate>
            <LocationConstraint>aws</LocationConstraint>
            <SSEConfiguration>
                <SSE>
                    <enabled>true</enabled>           ------Is this okay?
                </SSE>
                <SSE-KMS>
                    <enabled></enabled>         ---------What to provide here?
                    <DefaultKMSMasterKey></DefaultKMSMasterKey>  ------- What to provide here?
                </SSE-KMS>
            </SSEConfiguration>
        </Bucket>

**Comment by himanshuvar** [comment]
> > > > Hi @himanshuvar Could you please also add test for SSE feature?
> > > 
> > > 
> > > @sfzeng I don't know much about mult-cloud SSE. Could you please guide me the steps or a Demo for testing SSE?
> > 
> > 
> > yes, please check api/pkg/s3/bucketsseput.go.
> 
> @sfzeng I am not able to figure the API call request/response. Please provide the API spec for SSE.
> 
> ```
> <Bucket>
>             <Name>bucket1</Name>
>             <CreationDate>2020-04-10T20:20:08.000Z</CreationDate>
>             <LocationConstraint>aws</LocationConstraint>
>             <SSEConfiguration>
>                 <SSE>
>                     <enabled>true</enabled>           ------Is this okay?
>                 </SSE>
>                 <SSE-KMS>
>                     <enabled></enabled>         ---------What to provide here?
>                     <DefaultKMSMasterKey></DefaultKMSMasterKey>  ------- What to provide here?
>                 </SSE-KMS>
>             </SSEConfiguration>
>         </Bucket>
> ```

@sfzeng SSE is not working as per the Code available from multi-cloud. I have opened an issue.
https://github.com/sodafoundation/multi-cloud/issues/986

**Pull request merged**
