### PR TITLE
Documentation issue fix  in Multi-cloud Local Cluster Installation and Testing

### PR DESCRIPTION
**Pull request by vineela1999**
**What type of PR is this?**

 /kind bug fix

**What this PR does / why we need it**:
This PR fixes GO version mismatch in the documentation of Multi-cloud Local Cluster Installation and Testing
**Which issue(s) this PR fixes**:

Fixes # 
https://github.com/sodafoundation/multi-cloud/issues/1069

**Test Report Added?**:
Documentation fix
**Test Report**:
image

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by rajat-soda** [comment]
LGTM , Welcome to SODA , Congrats @vineela1999  on your First PR. !!

**Review by kumarashit — APPROVED** [review]
LGTM

**Review by skdwriting — APPROVED** [review]
LGTM

**Comment by skdwriting** [comment]
Please place documents to the documentation repo?

**Pull request merged**
