### PR TITLE
Issuefix for empty buckets missing without any filter & buckets with no objects showing with object level filter

### PR DESCRIPTION
**Pull request by josephjacobmorris**
**What type of PR is this?**
> /kind bug fix
> /kind enhancements

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
- fixing expires date coming as zero value if no value is provided
- empty buckets are missing in o/p for without any filter case fix
- adding document Id to o/p
- adding filtered aggregation fields
- fixing  buckets  with no objects after filtering also getting displayed when querying object level
- renaming fields as objectSizeInBytes,bucketSizeInBytes

Fixes #
#1392
**Test Report Added?**:
> /kind TESTED

**Test Report**:
-  empty buckets are missing in o/p for without any filter case fix
image

- adding document id to o/p
image

- adding filtered aggregation fields
image

- fixing  buckets  with no objects after filtering also getting displayed when querying object level
image

- renaming fields as objectSizeInBytes,bucketSizeInBytes
image

**Special notes for your reviewer**:

### CODE REVIEW

**Review by josephjacobmorris — COMMENTED** [review]
Self review done

**Comment by josephjacobmorris** [comment]
@devanshjain7  is also testing

**Review by devanshjain7 — APPROVED** [review]
LGTM

**Review by PravinRanjan10 — APPROVED** [review]
LGTM

**Pull request merged**
